// AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.
// Tiny blurred preview of /hero/kv-anniversary.jpg used as the Next <Image>
// blurDataURL so the hero appears instantly instead of flashing blank.
export const heroBlurDataURL =
  "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAADwAwCdASoYAA4APu1iqU2ppaOiMAgBMB2JZgCsACHwiVRMd+U8Jj4kAP7kR3tTptSS5zdhpdI662ZY9pEMN/oYxbSXyTvKLJQqG4kslOmmodOPRm/FTeF/fMdLS8+DeS0XCbCyBgAAAA==";
