// Web image optimizer for static brand/hero assets.
//
// Re-encodes oversized committed assets in `public/` in place and regenerates the
// hero blur placeholder consumed by the landing + about pages. Run after replacing
// any of these source assets:
//
//   npm run optimize:images
//
// Uses `sharp` (already a transitive dependency via Next's image pipeline), which
// ships the mozjpeg encoder and is far better suited to stills than ffmpeg.
//
// The originals always remain in git history, so re-running is safe — but note it
// re-compresses whatever is currently on disk, so don't run it twice expecting the
// same result from an already-optimized file.

import sharp from "sharp";
import { readFile, writeFile, stat } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const p = (rel) => path.join(root, rel);

const kb = (bytes) => `${(bytes / 1024).toFixed(1)} KB`;

async function sizeOf(file) {
  try {
    return (await stat(file)).size;
  } catch {
    return 0;
  }
}

async function logResize(label, file, before, after) {
  const pct = before ? Math.round((1 - after / before) * 100) : 0;
  console.log(`  ${label}: ${kb(before)} → ${kb(after)}  (-${pct}%)`);
}

// 1. Hero key visual — full-bleed background. 4K is wasteful for a darkened
//    backdrop; cap at 2560px and re-encode as progressive mozjpeg.
async function optimizeHero() {
  const file = p("public/hero/kv-anniversary.jpg");
  const before = await sizeOf(file);
  const input = await readFile(file);
  const out = await sharp(input)
    .resize({ width: 2560, withoutEnlargement: true })
    .jpeg({ quality: 78, progressive: true, mozjpeg: true })
    .toBuffer();
  await writeFile(file, out);
  await logResize("hero kv-anniversary.jpg", file, before, out.length);
  return input; // reuse the original (pre-resize) buffer for the blur LQIP
}

// 2. Blur LQIP — a tiny base64 WebP embedded inline so the hero never flashes
//    blank. Written as a generated TS module imported by the hero <Image>s.
async function generateHeroBlur(originalHeroBuffer) {
  const lqip = await sharp(originalHeroBuffer)
    .resize({ width: 24 })
    .blur()
    .webp({ quality: 40 })
    .toBuffer();
  const dataUrl = `data:image/webp;base64,${lqip.toString("base64")}`;
  const ts = `// AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.
// Tiny blurred preview of /hero/kv-anniversary.jpg used as the Next <Image>
// blurDataURL so the hero appears instantly instead of flashing blank.
export const heroBlurDataURL =
  "${dataUrl}";
`;
  const file = p("src/lib/hero-blur.ts");
  await writeFile(file, ts);
  console.log(`  hero blur LQIP: ${kb(lqip.length)} → src/lib/hero-blur.ts`);
}

// 3. HSR wordmark — displayed at most ~120px wide; the 500KB source is absurd.
//    Cap at 400px (retina-safe) and re-encode as an optimized palette PNG so the
//    transparent background and the existing `.png` references are preserved.
async function optimizeLogo() {
  const file = p("public/brand-marks/hsr-logo.png");
  const before = await sizeOf(file);
  const out = await sharp(await readFile(file))
    .resize({ width: 400, withoutEnlargement: true })
    .png({ compressionLevel: 9, palette: true, effort: 10 })
    .toBuffer();
  await writeFile(file, out);
  await logResize("hsr-logo.png", file, before, out.length);
}

async function main() {
  console.log("Optimizing static assets…");
  const heroOriginal = await optimizeHero();
  await generateHeroBlur(heroOriginal);
  await optimizeLogo();
  console.log("Done.");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
